### ISSUE TITLE
Project direction

### ISSUE THREAD

**Issue by caioalonso** [mitallast/diablo-js#5]
Hey, have you decided what will be the project's direction? Is it going to be a 100% replication of Diablo or just a similar engine but with different content?

**Comment by mitallast** [comment]
Hi!
100% is not real, I try make illusion of origin. Like another developers, I'm so badly designer, and I cannot create custom sprites like original. So I'm trying to get closer to the original.

This is don't mean, than there's no another content. Adding another content is easy, all my work - correctly render it, and extract it from original diablo. It's open source!

ps. Sorry for my english

**Comment by caioalonso** [comment]
It's fine :)

Do you have any roadmap in mind?

**Comment by mitallast** [comment]
No. But I see next step, and thinking about architecture and algorithms for monster walking, and big-map generator

**Comment by caioalonso** [comment]
I see. That seems like a good way to go. Thanks!
